/**
 * Voice → action-plan webhook endpoint (Phase 2).
 *
 * Request:
 *   POST /api/voice-microtask-webhook
 *   Authorization: Bearer <profiles.voice_webhook_token>
 *   Content-Type: multipart/form-data
 *   fields:
 *     audio: File (m4a/mp3/wav/...)
 *     idempotency_key: string (UUID generated by iOS Shortcut)
 *     audio_duration_ms: string (optional, integer)
 *
 * Pipeline (synchronous, ~3-7s typical):
 *   auth → idempotency check → quota check → upload to Storage
 *   → INSERT row(received) → STT (Groq → OpenAI) → hallucination filter
 *   → LLM classify into action plan (Groq Llama → Claude → OpenAI)
 *   → loop: validate + apply each action via INTENT_REGISTRY
 *   → UPDATE row(applied | error_*).
 *
 * Phase 2 changes:
 *   - LLM returns `actions: [{intent, payload}, ...]` (1..3 entries).
 *   - Dispatcher iterates, accumulates per-step summaries into final
 *     `applied_summary` shown in iOS push and in-app toast.
 *   - Response body includes `summary` so the iOS Shortcut can extract
 *     it via "Get Dictionary Value" and show as the notification.
 *
 * Returns 200 with { id, status, summary } even on processing failures so
 * the iPhone Shortcut can show a useful notification. 4xx/5xx are reserved
 * for auth/bad-request cases where retry is appropriate.
 */

import {
  countTodayForUser,
  findExistingByIdempotency,
  findProfileByVoiceToken,
  getServiceClient,
  insertReceivedRow,
  updateRow,
} from './_voice/db';
import { uploadAudio, downloadAudio } from './_voice/storage';
import { transcribeAudio } from './_voice/stt';
import { classifyVoice } from './_voice/llm';
import { INTENT_REGISTRY } from './_voice/intents';
import type {
  AppliedActionRecord,
  ApplyOutcome,
  LlmActionPlan,
  VoiceStatus,
  WebhookContext,
} from './_voice/types';

const DAILY_QUOTA_PER_USER = 200;

function jsonResponse(status: number, body: Record<string, unknown>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

/**
 * Roll up per-action outcomes into the legacy single-fields applied_task_id /
 * paused_task_id / undid_transcription_id columns. Pre-Phase-2 readers (sleep
 * webhook, history UI not yet built) still rely on those — so we populate
 * with the FIRST non-null value across all actions, which is sane for
 * common cases (single-action commands and undo+create chains).
 */
function rollupOutcome(outcomes: ApplyOutcome[]): {
  applied_task_id: string | null;
  paused_task_id: string | null;
  undid_transcription_id: string | null;
} {
  const pickFirst = <K extends keyof ApplyOutcome>(key: K): string | null => {
    for (const o of outcomes) {
      const v = o[key];
      if (typeof v === 'string') return v;
    }
    return null;
  };
  return {
    applied_task_id: pickFirst('applied_task_id'),
    paused_task_id: pickFirst('paused_task_id'),
    undid_transcription_id: pickFirst('undid_transcription_id'),
  };
}

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  // 1. Auth
  const authHeader = req.headers.get('authorization') ?? '';
  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token) {
    return new Response('Missing token', { status: 401 });
  }

  let supabase;
  try {
    supabase = getServiceClient();
  } catch (err) {
    return new Response((err as Error).message, { status: 500 });
  }

  const profile = await findProfileByVoiceToken(supabase, token).catch((err) => {
    console.error('voice-webhook: profile lookup failed', err);
    return null;
  });
  if (!profile) {
    return new Response('Invalid token', { status: 401 });
  }

  // 2. Multipart parse
  let formData: FormData;
  try {
    formData = await req.formData();
  } catch {
    return new Response('Expected multipart/form-data', { status: 400 });
  }

  const audioField = formData.get('audio');
  const idempotencyKey = (formData.get('idempotency_key') ?? '').toString().trim();
  const audioDurationRaw = (formData.get('audio_duration_ms') ?? '').toString().trim();

  if (!(audioField instanceof File) || audioField.size === 0) {
    return new Response('Missing or empty `audio` file field', { status: 400 });
  }
  if (!idempotencyKey) {
    return new Response('Missing `idempotency_key` field', { status: 400 });
  }
  const audioDurationMs = audioDurationRaw && /^\d+$/.test(audioDurationRaw)
    ? Number(audioDurationRaw)
    : null;

  // 3. Idempotency: same key already produced an outcome → return that.
  const existing = await findExistingByIdempotency(supabase, idempotencyKey).catch((err) => {
    console.error('voice-webhook: idempotency check failed', err);
    return null;
  });
  if (existing) {
    return jsonResponse(200, {
      id: existing.id,
      status: existing.status,
      summary: 'Уже обработано (повторный запрос).',
      idempotent: true,
    });
  }

  // 4. Daily quota
  try {
    const used = await countTodayForUser(supabase, profile.id);
    if (used >= DAILY_QUOTA_PER_USER) {
      return jsonResponse(429, {
        status: 'error_quota',
        summary: `Лимит на сегодня исчерпан (${DAILY_QUOTA_PER_USER}/день).`,
        detail: `daily quota ${DAILY_QUOTA_PER_USER} reached`,
      });
    }
  } catch (err) {
    console.warn('voice-webhook: quota check failed (non-fatal)', err);
  }

  // 5. Upload audio + INSERT row(received).
  let audioPath: string;
  let rowId: string;
  try {
    const uploaded = await uploadAudio(supabase, {
      userId: profile.id,
      file: audioField,
      idempotencyKey,
    });
    audioPath = uploaded.path;
    const created = await insertReceivedRow(supabase, {
      userId: profile.id,
      audioPath: uploaded.path,
      audioDurationMs,
      idempotencyKey,
    });
    rowId = created.id;
  } catch (err) {
    console.error('voice-webhook: upload/insert failed', err);
    return new Response((err as Error).message, { status: 500 });
  }

  const finishWith = async (
    status: VoiceStatus,
    summary: string,
    extras: Parameters<typeof updateRow>[2] = {},
  ) => {
    await updateRow(supabase, rowId, {
      status,
      processed_at: new Date().toISOString(),
      applied_summary: summary,
      ...extras,
    }).catch((err) => console.error('voice-webhook: final update failed', err));
    return jsonResponse(200, { id: rowId, status, summary });
  };

  // 6. Transition: received → processing.
  await updateRow(supabase, rowId, { status: 'processing' }).catch((err) => {
    console.warn('voice-webhook: processing transition failed (non-fatal)', err);
  });

  // 7. STT
  let audioBlob: Blob;
  try {
    audioBlob = await downloadAudio(supabase, audioPath);
  } catch (err) {
    return finishWith('error_stt', 'Не удалось прочитать аудио.', {
      error_detail: `download: ${(err as Error).message}`,
    });
  }
  const stt = await transcribeAudio(audioBlob, audioDurationMs);
  if (!stt.ok) {
    if (stt.reason === 'hallucination') {
      return finishWith('error_hallucination', 'Слышу только тишину — попробуй ещё.', {
        raw_transcript: stt.transcript ?? null,
        error_detail: stt.detail,
      });
    }
    if (stt.reason === 'too_short_audio') {
      return finishWith('error_stt', 'Запись слишком короткая.', { error_detail: stt.detail });
    }
    return finishWith('error_stt', 'Не разобрал звук.', { error_detail: stt.detail });
  }

  // 8. LLM action plan
  const ctx: WebhookContext = {
    userId: profile.id,
    voiceTargetWidgetId: profile.voice_target_widget_id,
    voiceTargetGoalsWidgetId: profile.voice_target_goals_widget_id,
    voiceIntentRules: profile.voice_intent_rules,
  };
  const llm = await classifyVoice(supabase, {
    userId: profile.id,
    transcript: stt.transcript,
    voiceIntentRules: profile.voice_intent_rules,
  });
  if (!llm.ok) {
    return finishWith('error_llm', 'Не смог классифицировать команду.', {
      raw_transcript: stt.transcript,
      error_detail: llm.detail,
    });
  }

  const plan: LlmActionPlan = llm.plan;
  if (plan.actions.length === 0) {
    return finishWith('error_llm', 'LLM не вернула ни одного действия.', {
      raw_transcript: stt.transcript,
      llm_output: plan,
    });
  }

  // 9. Apply every action in order. If any step fails, stop and report
  //    error_apply with whatever summary we already have (partial chain
  //    is preserved in applied_actions for debugging).
  const applied: AppliedActionRecord[] = [];
  const summaryParts: string[] = [];

  for (const action of plan.actions) {
    const spec = INTENT_REGISTRY[action.intent];
    if (!spec) {
      return finishWith(
        'error_unknown_intent',
        `Команда «${action.intent}» не поддерживается.`,
        {
          raw_transcript: stt.transcript,
          llm_output: plan,
          applied_actions: applied,
          error_detail: `intent "${action.intent}" is not in the registry`,
        },
      );
    }

    let validatedPayload: Record<string, unknown>;
    try {
      validatedPayload = spec.validatePayload(action.payload);
    } catch (err) {
      return finishWith('error_apply', 'Ошибка валидации payload\'а.', {
        raw_transcript: stt.transcript,
        llm_output: plan,
        applied_actions: applied,
        error_detail: `payload validation (${action.intent}): ${(err as Error).message}`,
      });
    }

    try {
      const result = await spec.apply(supabase, validatedPayload, ctx);
      applied.push({
        intent: action.intent,
        payload: validatedPayload,
        outcome: result.outcome,
        summary: result.summary,
      });
      if (result.summary) summaryParts.push(result.summary);
    } catch (err) {
      return finishWith('error_apply', 'Ошибка применения команды.', {
        raw_transcript: stt.transcript,
        llm_output: plan,
        applied_actions: applied,
        applied_intent: action.intent,
        applied_payload: validatedPayload,
        error_detail: (err as Error).message,
      });
    }
  }

  // 10. Successful end-state. Roll up per-action outcomes into the
  //     legacy applied_task_id / paused_task_id / undid_transcription_id
  //     columns so existing readers (Realtime hook, History UI) work
  //     without changes.
  const rolled = rollupOutcome(applied.map((a) => a.outcome));
  const summary = summaryParts.join(' + ');
  const firstAction = applied[0];
  return finishWith('applied', summary, {
    raw_transcript: stt.transcript,
    llm_output: plan,
    applied_intent: firstAction?.intent ?? null,
    applied_payload: firstAction?.payload ?? null,
    applied_actions: applied,
    applied_task_id: rolled.applied_task_id,
    paused_task_id: rolled.paused_task_id,
    undid_transcription_id: rolled.undid_transcription_id,
  });
}

export const config = {
  path: '/api/voice-microtask-webhook',
};
