/**
 * Voice → micro-task webhook endpoint.
 *
 * Request:
 *   POST /api/voice-microtask-webhook
 *   Authorization: Bearer <profiles.voice_webhook_token>
 *   Content-Type: multipart/form-data
 *   fields:
 *     audio: File (m4a/mp3/wav/...)
 *     idempotency_key: string (UUID generated by iOS Shortcut)
 *     audio_duration_ms: string (optional, integer)
 *
 * Pipeline (synchronous, ~3-5s typical):
 *   auth → idempotency check → quota check → upload to Storage
 *   → INSERT row(received) → STT (Groq, fallback OpenAI) → hallucination filter
 *   → LLM classify (Claude, fallback OpenAI) → INTENT_REGISTRY[intent].apply
 *   → UPDATE row(applied | error_*).
 *
 * Returns 200 with { id, status } even on processing failures so the iPhone
 * Shortcut treats them as "delivered" (audio is preserved server-side; the
 * UI surfaces the error to the user). Actual 4xx/5xx are reserved for auth
 * + bad-request cases where the Shortcut should NOT delete its local copy.
 */

import { findExistingByIdempotency, findProfileByVoiceToken, getServiceClient, insertReceivedRow, countTodayForUser, updateRow } from './_voice/db';
import { uploadAudio, downloadAudio } from './_voice/storage';
import { transcribeAudio } from './_voice/stt';
import { classifyVoice } from './_voice/llm';
import { INTENT_REGISTRY } from './_voice/intents';
import type { VoiceStatus, WebhookContext } from './_voice/types';

const DAILY_QUOTA_PER_USER = 200;

function jsonResponse(status: number, body: Record<string, unknown>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  // 1. Auth
  const authHeader = req.headers.get('authorization') ?? '';
  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token) {
    return new Response('Missing token', { status: 401 });
  }

  let supabase;
  try {
    supabase = getServiceClient();
  } catch (err) {
    return new Response((err as Error).message, { status: 500 });
  }

  const profile = await findProfileByVoiceToken(supabase, token).catch((err) => {
    console.error('voice-webhook: profile lookup failed', err);
    return null;
  });
  if (!profile) {
    return new Response('Invalid token', { status: 401 });
  }

  // 2. Multipart parse
  let formData: FormData;
  try {
    formData = await req.formData();
  } catch {
    return new Response('Expected multipart/form-data', { status: 400 });
  }

  const audioField = formData.get('audio');
  const idempotencyKey = (formData.get('idempotency_key') ?? '').toString().trim();
  const audioDurationRaw = (formData.get('audio_duration_ms') ?? '').toString().trim();

  if (!(audioField instanceof File) || audioField.size === 0) {
    return new Response('Missing or empty `audio` file field', { status: 400 });
  }
  if (!idempotencyKey) {
    return new Response('Missing `idempotency_key` field', { status: 400 });
  }
  const audioDurationMs = audioDurationRaw && /^\d+$/.test(audioDurationRaw)
    ? Number(audioDurationRaw)
    : null;

  // 3. Idempotency: same key already produced an outcome → return that.
  const existing = await findExistingByIdempotency(supabase, idempotencyKey).catch((err) => {
    console.error('voice-webhook: idempotency check failed', err);
    return null;
  });
  if (existing) {
    return jsonResponse(200, { id: existing.id, status: existing.status, idempotent: true });
  }

  // 4. Daily quota
  try {
    const used = await countTodayForUser(supabase, profile.id);
    if (used >= DAILY_QUOTA_PER_USER) {
      return jsonResponse(429, { status: 'error_quota', detail: `daily quota ${DAILY_QUOTA_PER_USER} reached` });
    }
  } catch (err) {
    // Non-fatal: log and proceed. Better to risk one-off overage than to drop a recording.
    console.warn('voice-webhook: quota check failed (non-fatal)', err);
  }

  // 5. Upload audio + INSERT row(received).
  let audioPath: string;
  let rowId: string;
  try {
    const uploaded = await uploadAudio(supabase, {
      userId: profile.id,
      file: audioField,
      idempotencyKey,
    });
    audioPath = uploaded.path;
    const created = await insertReceivedRow(supabase, {
      userId: profile.id,
      audioPath: uploaded.path,
      audioDurationMs,
      idempotencyKey,
    });
    rowId = created.id;
  } catch (err) {
    console.error('voice-webhook: upload/insert failed', err);
    return new Response((err as Error).message, { status: 500 });
  }

  const finishWith = async (
    status: VoiceStatus,
    extras: Parameters<typeof updateRow>[2] = {},
  ) => {
    await updateRow(supabase, rowId, {
      status,
      processed_at: new Date().toISOString(),
      ...extras,
    }).catch((err) => console.error('voice-webhook: final update failed', err));
    return jsonResponse(200, { id: rowId, status });
  };

  // 6. Transition: received → processing.
  await updateRow(supabase, rowId, { status: 'processing' }).catch((err) => {
    console.warn('voice-webhook: processing transition failed (non-fatal)', err);
  });

  // 7. STT
  let audioBlob: Blob;
  try {
    audioBlob = await downloadAudio(supabase, audioPath);
  } catch (err) {
    return finishWith('error_stt', { error_detail: `download: ${(err as Error).message}` });
  }
  const stt = await transcribeAudio(audioBlob, audioDurationMs);
  if (!stt.ok) {
    if (stt.reason === 'hallucination') {
      return finishWith('error_hallucination', {
        raw_transcript: stt.transcript ?? null,
        error_detail: stt.detail,
      });
    }
    return finishWith('error_stt', { error_detail: stt.detail });
  }

  // 8. LLM
  const ctx: WebhookContext = {
    userId: profile.id,
    voiceTargetWidgetId: profile.voice_target_widget_id,
    voiceIntentRules: profile.voice_intent_rules,
  };
  const llm = await classifyVoice(supabase, {
    userId: profile.id,
    transcript: stt.transcript,
    voiceIntentRules: profile.voice_intent_rules,
  });
  if (!llm.ok) {
    return finishWith('error_llm', {
      raw_transcript: stt.transcript,
      error_detail: llm.detail,
    });
  }

  const classification = llm.classification;
  const spec = INTENT_REGISTRY[classification.intent];
  if (!spec) {
    return finishWith('error_unknown_intent', {
      raw_transcript: stt.transcript,
      llm_output: classification,
      error_detail: `intent "${classification.intent}" is not in the registry`,
    });
  }

  // 9. Apply
  let validatedPayload: Record<string, unknown>;
  try {
    validatedPayload = spec.validatePayload(classification.payload);
  } catch (err) {
    return finishWith('error_apply', {
      raw_transcript: stt.transcript,
      llm_output: classification,
      error_detail: `payload validation: ${(err as Error).message}`,
    });
  }

  try {
    const outcome = await spec.apply(supabase, validatedPayload, ctx);
    return finishWith('applied', {
      raw_transcript: stt.transcript,
      llm_output: classification,
      applied_intent: classification.intent,
      applied_payload: validatedPayload,
      applied_task_id: outcome.applied_task_id ?? null,
      paused_task_id: outcome.paused_task_id ?? null,
    });
  } catch (err) {
    return finishWith('error_apply', {
      raw_transcript: stt.transcript,
      llm_output: classification,
      applied_intent: classification.intent,
      applied_payload: validatedPayload,
      error_detail: (err as Error).message,
    });
  }
}

export const config = {
  path: '/api/voice-microtask-webhook',
};
